version: 2.1
jobs:
  build_and_publish:
    docker:
      - image: cimg/node:18.12
    steps:
      - save_cache:
          key: v1-cache
          paths:
            - project/
      - checkout
      - run:
          name: Install packages
          command: |
            npm install
      - run:
          name: Authenticate with registry
          command: |
            echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > ./.npmrc
      - run:
          name: Publish packages
          command: |
            cd ~/project/packages/core && npm publish || true
            cd ~/project/packages/laudspeaker-js && npm publish || true
            cd ~/project/packages/react && npm publish || true
            cd ~/project/packages/react-native && npm publish || true

workflows:
  main:
    jobs:
      - build_and_publish:
          filters:
            branches:
              only:
                - main
